myshop/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),

]

myshop/coupons/urls.py
from django.urls import path
from .views import *


app_name = 'coupons'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import logout
from rest_framework import routers
from shop.views import *

# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'groups', GroupViewSet)
# router.register(r'product_api', ProductsViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('drf/', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('coupons/', include('coupons.urls')),
    path('payment/', include('payment.urls')),
    path('order/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
    path('oauth/', include('social_django.urls', namespace ='social')),
    path('accounts/', include('allauth.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create_order/', order_create, name = 'order_create'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name = 'admin_order_pdf'),
    path('test1/', home, name='home'),
]

myshop/shop/urls.py
from django.urls import path,include
from .views import *
from rest_framework import routers


#маршруты для контроллера API сзоданного через класс ViewSets
# router = routers.DefaultRouter() # создали объект DefaultRouter
# router.register('products', ProductViewsSet) # зарегали набор обработчиков с префиксом products


urlpatterns = [
    path('', index, name='index'),
    path('list/<str:slug>', product_list, name='product_list'),
    # path('<int:product_id>/<str:slug>/', product_detail, name='product_detail'),
    path('<int:category_id>/', category_product, name='category_product'),
    path('<int:product_id>', product_detail, name='product_detail'),
    path('accounts/registration/', register_user, name='registration'),
    path('subscriber/',subscriber_user, name='subscriber'),
    path('update_product/<int:product_id>', UpdateProduct, name='update_product'),
    path('api/product/', ProductList.as_view(), name='api_product'),
    # path('api/product/<pk>/', ProductDetailView.as_view(), name='product_detail_api'),
    # path('api/', include(router.urls)),


    # path('', include('social_django.urls')),

]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length = 100, db_index=True, verbose_name='Наименование')
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('product_list', kwargs={'slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название товара')
    image = models.ImageField(upload_to='photo/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    description = models.TextField(verbose_name='Описание товара', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('product_detail', kwargs={'product_id': self.pk})


class Subscriber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'


# Create your models here.

myshop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

# quantity - поле которое отображает какое чилсо нужно доьавить в коризну(предусмотренные значения от 1 до 20)
# используем класс TypedChoiceField с параметром coerce=int, чтобы автоматически преобразовывать
# выбранное значение в целое число
# update – обновить (значение True) или заменить (значение False) количество единиц для товара.
# Мы используем тип поля HiddenInput, чтобы пользователь не видел его в своей форме.

myshop/shop/forms.py
from django import forms
from .models import *


class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'price', 'available', 'description']

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .forms import *
from .cart import Cart
from django.views.decorators.http import require_POST
from coupons.forms import *
from shop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended = r.suggest_products_for(cart_products, max_results=4)
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form,
                                                'recommended': recommended})


# Create your views here.

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from .models import *
from cart.forms import CartAddProductForm
from .recommender import Recommender
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives # отправка писем с разным содержимым
from django.template.loader import get_template
from django.dispatch import receiver
from django.db.models.signals import post_save
from shop.tasks import send_product_mail
from django.core.cache import cache
from .forms import *



@login_required(login_url='/accounts/login/')
def index(request):
    context = Product.objects.all()[:4]
    num_visit = request.session.get('num_visit',0)
    request.session['num_visit'] = num_visit + 1
    # visit = cache.get_or_set('num_visit', num_visit, 10)
    return render(request, 'shop/index.html', {'context': context, 'num_visits':num_visit,})


@login_required()
def product_list(request, slug):
    categories = Category.objects.filter(slug=slug)
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product_list.html', {'products': products,'categories': categories})


# @login_required()
# def product_detail(request, slug, product_id):
#     product_object = get_object_or_404(Product, slug=slug, pk=product_id)
#     return render(request, {'product_obj': product_object, 'form': cart_product_form})
# Create your views here.


#товары по категориям
@login_required()
def category_product(request, category_id):
    context = Product.objects.filter(category_id=category_id)
    return render(request, 'shop/category_product.html', {'context': context})


def product_detail(request, product_id):
    object = get_object_or_404(Product, pk=product_id)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    bought_product = r.products_bought([object])
    print(bought_product)
    recommended_products = r.suggest_products_for([object],4)
    print(recommended_products)
    return render(request, 'shop/single_product.html', {'object':object,'form': cart_product_form,
                                                        'recommended': recommended_products})


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
    return render(request,'registration/registration.html', {'form':form})


def subscriber_user(request):
    if request.method == 'POST':
        form = forms.Form(request.POST)
        if form.is_valid():
            created = Subscriber.objects.get_or_create(user=request.user)
        return redirect('/')


def send_mail_product(product_id):
    data = Product.objects.get(name=product_id)
    subject = 'Новинка недели'
    from_email = 'bigmama93@mail.ru'
    mail = Subscriber.objects.values('user__email')
    to = []
    for i in mail:
        to.append(i['user__email'])
    html_content = get_template('shop/mail/product_week.html')
    context = {'product': data}
    html_render = html_content.render(context)
    msg = EmailMultiAlternatives(subject=subject,body=html_render,to=to, from_email=from_email)
    msg.attach_alternative(html_render, 'text/html')
    msg.send()


@receiver(post_save, sender=Product)
def send_for_product_week(instance,created,**kwargs):
    if created:
        send_product_mail.delay(instance.name)


def UpdateProduct(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = UpdateProductForm(request.POST, instance=product) # при редактировании передаем объект product в аргумент
        # instance
        if form.is_valid():
            product_update = product.save()
            return redirect(product)
    else:
        form = UpdateProductForm(instance=product)
    return render(request, 'shop/update_product.html', {'form': form})


"""
здесь будет описываться приложение для DRF
"""

from django.contrib.auth.models import User,Group
from rest_framework import viewsets,permissions
from shop.serializers import  ProductSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import generics

# class UserViewSet(viewsets.ModelViewSet):
#     """
#     Конечная точка API, которая позволяет просматривать или редактировать пользователей.
#     """
#     queryset = User.objects.all().order_by('-date_joined')
#     serializer_class = UserSerializer
#     permission_classes = [permissions.IsAuthenticated]
#
#
# class GroupViewSet(viewsets.ModelViewSet):
#     queryset = Group.objects.all()
#     serializer_class = GroupSerializer
#     permission_classes = [permissions.IsAuthenticated]
#
#
# # class ProductsViewSet(viewsets.ModelViewSet):
# #     queryset = Product.objects.all()
# #     serializer_class = ProductSerializer
# #     permission_classes = [permissions.IsAuthenticated]
#
# @api_view(['GET'])
# def api_product(request):
#     if request.method == 'GET':
#         queryset = Product.objects.all()
#         serializer = ProductSerializer(queryset, many = True) # many значит что нужно показывать все объекты
#         return Response(serializer.data)
#
#
# #сведения о каждом продукте
# @api_view(['GET'])
# def api_product_detail(request, product_id):
#     if request.method == 'GET':
#         queryset = Product.objects.filter(pk=product_id)
#         serializer =ProductSerializer(queryset)
#         return Response(serializer.data)
#
#
# #свдеения о продуктах через класс
# class ProductListView(generics.ListAPIView):  # только для чтения для представления коллекции экземпляров модели .
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer
#
#
# class ProductDetailView(generics.RetrieveAPIView):  # только для чтения для представления одного экземпляра модели .
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer
#
#
# class ProductViewsSet(viewsets.ReadOnlyModelViewSet):
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer


from rest_framework.views import APIView


class ProductList(APIView): # апи для всех сниппетов, реализованный через CBV
    """
    Отображает все сниппеты или создает новый сниппет.
    """
    # authentication_classes = [SessionAuthentication, BasicAuthentication]
    # permission_classes = [IsAuthenticated]
    def get(self, request, format=None):
        snippet = Product.objects.all()
        serializer = ProductSerializer(snippet, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

myshop/shop/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load _mytag %}

{% block sidebar %}
<div id="navigation" xmlns="http://www.w3.org/1999/html">
	<!-- container -->
	<div class="container">
		<div id="responsive-nav">
			<!-- category nav -->
			<div class="category-nav show-on-click">
				<span class="category-header">Categories <i class="fa fa-list"></i></span>
				<ul class="category-list">
					<li class="dropdown side-dropdown">
						{% sidebar as category %}
						{% for cat in category %}
					<li><a href="{% url 'category_product' cat.slug %}">{{cat.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<!-- /category nav -->

			<!-- menu nav -->
			<div class="menu-nav">
				<span class="menu-header">Menu <i class="fa fa-bars"></i></span>
				<ul class="menu-list">
					<li class="dropdown mega-dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">Women <i class="fa fa-caret-down"></i></a>
						<div class="custom-menu">
							<div class="row">
								<div class="col-md-4">
									<ul class="list-links">
										<li>
											<h3 class="list-links-title">Categories</h3></li>
										<li><a href="#">Women’s Clothing</a></li>
									</ul>
									<hr class="hidden-md hidden-lg">
								</div>
								<div class="col-md-4">
									<ul class="list-links">
										<li>
											<h3 class="list-links-title">Categories</h3></li>
										<li><a href="#">Women’s Clothing</a></li>
									</ul>
									<hr class="hidden-md hidden-lg">
								</div>
								<div class="col-md-4">
									<ul class="list-links">
										<li>
											<h3 class="list-links-title">Categories</h3></li>
										<li><a href="#">Bags & Shoes</a></li>
									</ul>
								</div>
							</div>
						</div>
					</li>
					<li><a href="#">Sales</a></li>
				</ul>
			</div>
			<!-- menu nav -->
		</div>
	</div>
	<!-- /container -->
</div>
{% endblock %}




{% block content %}
<body>
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="#">Home</a></li>
				<li class="active">Checkout</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% comment %}
				<form id="checkout-form" class="_blank">
					<div class="col-md-6">
						<div class="billing-details">
							<p>Already a customer ? <a href="#">Login</a></p>
							<div class="section-title">
								<h3 class="title">Billing Details</h3>
							</div>
							<div class="form-group">
								<input class="input" type="text" name="first-name" placeholder="First Name">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="last-name" placeholder="Last Name">
							</div>
							<div class="form-group">
								<input class="input" type="email" name="email" placeholder="Email">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="address" placeholder="Address">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="city" placeholder="City">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="country" placeholder="Country">
							</div>
							<div class="form-group">
								<input class="input" type="text" name="zip-code" placeholder="ZIP Code">
							</div>
							<div class="form-group">
								<input class="input" type="tel" name="tel" placeholder="Telephone">
							</div>
							<div class="form-group">
								<div class="input-checkbox">
									<input type="checkbox" id="register">
									<label class="font-weak" for="register">Create Account?</label>
									<div class="caption">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
											<p>
												<input class="input" type="password" name="password" placeholder="Enter Your Password">
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-6">
						<div class="shiping-methods">
							<div class="section-title">
								<h4 class="title">Shiping Methods</h4>
							</div>
							<div class="input-checkbox">
								<input type="radio" name="shipping" id="shipping-1" checked>
								<label for="shipping-1">Free Shiping -  $0.00</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
										<p>
								</div>
							</div>
							<div class="input-checkbox">
								<input type="radio" name="shipping" id="shipping-2">
								<label for="shipping-2">Standard - $4.00</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
										<p>
								</div>
							</div>
						</div>

						<div class="payments-methods">
							<div class="section-title">
								<h4 class="title">Payments Methods</h4>
							</div>
							<div class="input-checkbox">
								<input type="radio" name="payments" id="payments-1" checked>
								<label for="payments-1">Direct Bank Transfer</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
										<p>
								</div>
							</div>
							<div class="input-checkbox">
								<input type="radio" name="payments" id="payments-2">
								<label for="payments-2">Cheque Payment</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
										<p>
								</div>
							</div>
							<div class="input-checkbox">
								<input type="radio" name="payments" id="payments-3">
								<label for="payments-3">Paypal System</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
										<p>
								</div>
							</div>
						</div>
					</div>
                </form>
				{% endcomment %}
					<div class="col-md-12">
						<div class="order-summary clearfix">
							<div class="section-title">
								<h3 class="title">Order Review</h3>
							</div>
							<table class="shopping-cart-table table">
								<thead>
									<tr>
										<th>Product</th>
										<th></th>
										<th class="text-center">Price</th>
										<th class="text-center">Quantity</th>
										<th class="text-center">Total</th>
										<th class="text-right"></th>
									</tr>
								</thead>
								<tbody>
                                    {% for item in cart %}
                                    {% with product=item.product %}
									<tr>
                                        {% if product.image %}
										<td class="thumb"><img src="{{product.image.url}}" alt=""></td>
                                        {% else %}
                                        <td class="thumb"><img src="{% static 'shop/img/no-logo.jpg' %}" alt=""></td>
                                        {% endif %}
										<td class="details">
											<a href="#">{{product.name}}</a>
											<ul>
												<li><span>Size: XL</span></li>
												<li><span>Color: Camelot</span></li>
											</ul>
										</td>
										<td class="price text-center"><strong>{{item.price}}</strong><br><del class="font-weak"><small>$40.00</small></del></td>
                                        <td class="qty text-center">
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                {{item.update_quantity_form.quantity}}
                                                {{ item.update_quantity_form.update }}
                                                <input type="submit" value="Update">
                                                {% csrf_token %}
                                            </form>
                                        </td>
										<td class="total text-center"><strong class="primary-color">{{item.total_price}}</strong></td>
                                        <td class="text-right">
                                            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                                {% csrf_token %}
                                                <button class="main-btn icon-btn"><i class="fa fa-close"></i></button>
                                            </form>
                                        </td>
									</tr>
                                {% endwith %}
                                {% endfor %}


								</tbody>
								<tfoot>
									<tr>
										<th class="empty" colspan="3"></th>
										<th>SUBTOTAL</th>
										<th colspan="2" class="sub-total">{{cart.total_price}}</th>
									</tr>
									<tr>
										<th class="empty" colspan="3"></th>
										<th>SHIPING</th>
										<td colspan="2">Free Shipping</td>
									</tr>
									{% if cart.coupon %}
									<tr>
										<th class="empty" colspan="3"></th>
										<th>SALE</th>

										<td colspan="2">{{cart.get_discount}}</td>
									</tr>
									{% endif %}
									<tr>
										<th class="empty" colspan="3"></th>
										<th>TOTAL</th>
										<th colspan="2" class="total">{{cart.get_price_include_discount}}</th>
									</tr>


								</tfoot>

							</table>
							<p> <strong>ПРОМОКОД:</strong></p>
							<form action="{% url 'coupons:apply' %}" method="post">
								{{ coupon_apply_form }}
								<input type="submit" value="Применить">
								{% csrf_token %}
							</form>
							<div class="pull-right">
								<form action="{% url 'orders:order_create' %}" method="get">
									<button class="primary-btn">Place Order</button>
								</form>
							</div>
						</div>

					</div>

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% if recommended %}
<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">С этим товаром так же покупают:</h2>
					</div>
				</div>
				<!-- section title -->
				{% for p in recommended %}
				<!-- Product Single -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<div class="product-thumb">
							<button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</button>
							{% if p.image %}
							<img src="{{p.image.url}}"  alt="" height="220" width="180">
							{% endif %}
						</div>
						<div class="product-body">
							<h3 class="product-price">{{p.price}}</h3>
							<div class="product-rating">
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i>
							</div>
							<h2 class="product-name"><a href="{{p.get_absolute_url}}">{{p.name}}</a></h2>
							<div class="product-btns">
								<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<!-- /Product Single -->

			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
{% endif %}

	<!-- jQuery Plugins -->
	<script src="js/jquery.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/slick.min.js"></script>
	<script src="js/nouislider.min.js"></script>
	<script src="js/jquery.zoom.min.js"></script>
	<script src="js/main.js"></script>

</body>
{% endblock %}